server:
  port: 8080
  error:
    include-message: always

spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: hakker7707
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
